# Generated by Django 3.2 on 2021-04-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_users_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='repwd',
        ),
    ]
